language: ruby
rvm: 2.1.1
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
notifications:
  webhooks:
    urls:
      - secure: "V1/iGxLwuko+pLZVG31A5B14E2Vhkhh2DS3aKF/zmVXDqoEgl5+d8CWy03prvemKHCgDW9rOZJGtixTJGViJwF2hGo/wHbSPS2cTghbKYNEM7pSwjnzg1BwUGeYxz9bfPZUSWFRK7W1RdEtm2EaOQ63JAFIqjPz6jUh8reDlMik="
script: bundle exec rake
