source "https://rubygems.org"

gem "rails"
gem "pg"
gem "uglifier"
gem "coffee-rails"
gem "therubyracer", platforms: :ruby
gem "jquery-rails"
gem "slim"
gem "less-rails"
gem "foreman"
gem "puma"
gem "dotenv-rails"
gem "redcarpet"
gem "omniauth-github"
gem "grocer"
gem "push_package"
gem "quiet_assets"
