source "https://rubygems.org"

ruby "2.1.1"

gem "rails"
gem "pg"
gem "uglifier"
gem "coffee-rails"
gem "therubyracer", platforms: :ruby
gem "jquery-rails"
gem "slim"
gem "less-rails"
gem "foreman"
gem "foreman-capistrano"
gem "puma"
gem "dotenv-rails"
gem "redcarpet"
gem "omniauth-github"
gem "houston"
gem "push_package"
gem "capistrano"
