#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

run() {
  /home/git/.rbenv/bin/rbenv exec ruby
}

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive

run deploy/before_restart
run deploy/restart && run deploy/after_restart
