#!/usr/bin/env bash

export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"

set -e

bin/bundle install --without development:test
bin/bundle clean
bin/dotenv bin/rake db:create db:migrate
rbenv sudo bin/foreman export upstart -u git /etc/init -l log -a spansy-data
sudo service spansy-data restart
