development:
  adapter: postgresql
  encoding: unicode
  database: space_notice_development

test:
  adapter: postgresql
  encoding: unicode
  database: space_notice_test

production:
  adapter: postgresql
  encoding: unicode
  database: space_notice_production
